# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNFBTestProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFBTestProject
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'RNFBTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

